--- 
jobs: 
  docker-build: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:2022.04.1"
      resource_class: medium
    steps: 
      - 
        checkout: 
          path: ~/app
      - 
        run: 
          command: "docker build --build-arg FRESHRSS_VERSION=1.19.2 ."
          name: "Test Build"
    working_directory: ~/app
version: 2.1
workflows: 
  default: 
    jobs: 
      - docker-build